## Application settings
spring.application.name=synk
server.servlet.context-path=/synk
server.port=8080
#Spring framework caching
#logging.level.org.springframework=DEBUG

# Set log levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Enable file logging
logging.file.name=logs/app.log

# Customize log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Cache Logging
logging.level.org.springframework.cache=TRACE

#spring.profiles.active=${SPRING_PROFILES_ACTIVE}







