# ==============================
# JWT secret
# ==============================
jwt.secret=${JWT_SECRET}

# ==============================
# MySQL Database
# ==============================
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# Hibernate / JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# HikariCP Connection Pool
# ==============================
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${HIKARI_MINIMUM_IDLE}
spring.datasource.hikari.idle-timeout=${HIKARI_IDLE_TIMEOUT}
spring.datasource.hikari.connection-timeout=${HIKARI_CONNECTION_TIMEOUT}
spring.datasource.hikari.max-lifetime=${HIKARI_MAX_LIFETIME}
spring.datasource.hikari.pool-name=${HIKARI_POOL_NAME}

# ==============================
# Redis Cache
# ==============================
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.cache.type=redis
spring.redis.lettuce.shutdown-timeout=100ms
spring.redis.timeout=2000
# ==============================
# Email (Gmail SMTP)
# ==============================
email.host=${EMAIL_HOST}
email.port=${EMAIL_PORT}
email.username=${EMAIL_USERNAME}
email.password=${EMAIL_PASSWORD}
email.from=${EMAIL_FROM}

# ==============================
# RabbitMQ
# ==============================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
